##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ######
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/qrsmco/repositories/qrs24/
    #Copy the specific file to the destination from root:
    - cp . $DEPLOYPATH
